# Generated by Django 3.0.8 on 2020-08-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_book_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(blank=True, default='exit'),
            preserve_default=False,
        ),
    ]
