# Generated by Django 3.0.8 on 2020-08-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amount',
            field=models.IntegerField(default=110),
            preserve_default=False,
        ),
    ]
