# Generated by Django 3.0.8 on 2020-08-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_book_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='amount',
            new_name='price',
        ),
    ]
