# Generated by Django 3.0.8 on 2020-08-11 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200811_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.AddField(
            model_name='publication',
            name='book',
            field=models.ForeignKey(default='book', on_delete=django.db.models.deletion.CASCADE, to='dashboard.Book'),
            preserve_default=False,
        ),
    ]
