# Generated by Django 3.0.8 on 2020-08-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200811_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='book',
        ),
    ]
